version: '3'

volumes:
  server_sales_manager_local_postgres_data: {}
  server_sales_manager_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: server_sales_manager_local_django
    container_name: server_sales_manager_local_django
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: server_sales_manager_production_postgres
    container_name: server_sales_manager_local_postgres
    volumes:
      - server_sales_manager_local_postgres_data:/var/lib/postgresql/data:Z
      - server_sales_manager_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: server_sales_manager_local_mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: server_sales_manager_local_redis

  celeryworker:
    <<: *django
    image: server_sales_manager_local_celeryworker
    container_name: server_sales_manager_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: server_sales_manager_local_celerybeat
    container_name: server_sales_manager_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: server_sales_manager_local_flower
    container_name: server_sales_manager_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
